# Generated by Django 5.2.7 on 2025-10-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='season',
            field=models.CharField(choices=[('Spring', 'spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=100),
        ),
    ]
