# Generated by Django 5.2.7 on 2025-10-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_stamp_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='season',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=100),
        ),
    ]
