# Generated by Django 5.2.7 on 2025-10-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_stamp_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='name',
            field=models.CharField(choices=[('United States', '🇺🇸 United States'), ('Canada', '🇨🇦 Canada'), ('Mexico', '🇲🇽 Mexico'), ('Brazil', '🇧🇷 Brazil'), ('United Kingdom', '🇬🇧 United Kingdom'), ('Germany', '🇩🇪 Germany'), ('France', '🇫🇷 France'), ('Italy', '🇮🇹 Italy'), ('Spain', '🇪🇸 Spain'), ('Netherlands', '🇳🇱 Netherlands'), ('Switzerland', '🇨🇭 Switzerland'), ('Sweden', '🇸🇪 Sweden'), ('Australia', '🇦🇺 Australia'), ('Japan', '🇯🇵 Japan'), ('South Korea', '🇰🇷 South Korea'), ('China', '🇨🇳 China'), ('India', '🇮🇳 India'), ('South Africa', '🇿🇦 South Africa'), ('United Arab Emirates', '🇦🇪 United Arab Emirates'), ('Argentina', '🇦🇷 Argentina')], max_length=100),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=100),
        ),
    ]
