# Generated by Django 5.2.7 on 2025-10-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_stamp_name_alter_stamp_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='name',
            field=models.CharField(choices=[('United States', '🇺🇸 United States'), ('Canada', '🇨🇦 Canada'), ('Mexico', '🇲🇽 Mexico'), ('Brazil', '🇧🇷 Brazil'), ('United Kingdom', '🇬🇧 United Kingdom'), ('Germany', '🇩🇪 Germany'), ('France', '🇫🇷 France'), ('Italy', '🇮🇹 Italy'), ('Spain', '🇪🇸 Spain'), ('Netherlands', '🇳🇱 Netherlands'), ('Switzerland', '🇨🇭 Switzerland'), ('Sweden', '🇸🇪 Sweden'), ('Australia', '🇦🇺 Australia'), ('Japan', '🇯🇵 Japan'), ('South Korea', '🇰🇷 South Korea'), ('China', '🇨🇳 China'), ('India', '🇮🇳 India'), ('South Africa', '🇿🇦 South Africa'), ('United Arab Emirates', '🇦🇪 United Arab Emirates'), ('Argentina', '🇦🇷 Argentina')], default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], default='spring', max_length=100),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rating', models.IntegerField(choices=[(5, '⭐️⭐️⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (3, '⭐️⭐️⭐️'), (2, '⭐️⭐️'), (1, '⭐️')], default=5)),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.stamp')),
            ],
        ),
    ]
