# Generated by Django 5.2.7 on 2025-10-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_stamp_name_alter_stamp_season_stop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='stop',
            name='date',
            field=models.DateField(verbose_name='Visit Date'),
        ),
    ]
